# index_flows.ps1 - generate flows/manifest.json: a quick-reference index of this ratchet's action chains
# (id + summary + entry + node count) read from each flows/<chain>/chain.json. An agent reads this ONE
# file to learn what flows exist and what each does, instead of opening every chain.json. Re-run after
# adding or changing a flow. (Domain-agnostic utility; mirrors how kb/manifest.json indexes the kb.) Run
# from the ratchet root.
param()
$ErrorActionPreference = "Stop"

if (-not (Test-Path "flows")) { Write-Output "no flows/ dir (run from the ratchet root)"; exit 1 }

$flows = @()
foreach ($d in (Get-ChildItem "flows" -Directory | Sort-Object Name)) {
    $cj = Join-Path $d.FullName "chain.json"
    if (-not (Test-Path $cj)) { continue }
    try { $c = Get-Content -Raw $cj | ConvertFrom-Json } catch { continue }
    $flows += [pscustomobject]@{
        id      = $c.id
        summary = $c.summary
        entry   = $c.entry
        nodes   = @($c.nodes).Count
    }
}

$out = [pscustomobject]@{
    '$comment' = 'Quick-reference index of this ratchet flows (id + summary + entry + node count). Generated by tools/index_flows.ps1 - re-run after adding or changing a flow. The engine discovers flows by scanning each flow folder chain.json; this file is for fast human/agent reference.'
    flows      = $flows
}
$json = $out | ConvertTo-Json -Depth 5
[System.IO.File]::WriteAllText((Join-Path "flows" "manifest.json"), $json, (New-Object System.Text.UTF8Encoding $false))
Write-Output ("wrote flows/manifest.json (" + $flows.Count + " flows)")
exit 0
